# Read the full reference here: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Achievements 
on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push: { branches: ["master", "main", "metrics"] }
jobs:
  # https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/README.md
  achievement-metrics:      
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.achievements.svg

          # Options
          user: Anmol-Baranwal
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
