# Read the full reference here: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Lines of Code Changed
on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push: { branches: ["master", "main", "metrics"] }
jobs:
  # https://github.com/lowlighter/metrics/blob/master/source/plugins/lines/README.md
  code-lines-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.code.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_skipped: testing, The-Futurists_Manthan_Frontend
          plugin_lines_repositories_limit: 4
