# Read the full reference here: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Follow up Issues and PRs
on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push: { branches: ["master", "main", "metrics"] }
jobs:
  # https://github.com/lowlighter/metrics/blob/master/source/plugins/followup/README.md
  follow-up-pr-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
