# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics Combined
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  follow-up-pr-metrics:
      runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories, user
  achievements-metrics:
      runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.achievements.svg

          # Options
          user: Anmol-Baranwal
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
  discussions-metrics:
      runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.discussions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_discussions: yes
  leetcode-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: anmol4coder
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_recent: 5
          plugin_leetcode_limit_skills: 7
  notable-contributions-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.notable.contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request
          plugin_notable_filter: stars:>=500
  code-lines-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.code.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_lines_sections: base, repositories, history
          plugin_lines_repositories_limit: 5
          plugin_lines_history_limit: 1
  languages-activity-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.languages.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes   # do not use it, this may leak important company code
          plugin_languages_other: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, percentage # Note that lines is only available when plugin_languages_indepth is enabled
          plugin_languages_limit: 7   # limit is 8
          plugin_languages_analysis_timeout: 15
  reaction-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 300
          plugin_reactions_details: percentage
          
          
  
